// mksysnum_linux.pl /usr/include/asm/unistd_32.h
// Code generated by the command above; DO NOT EDIT.

package std

import . "syscall"

var syscallNum = map[string]ScmpSyscall{
	"restart_syscall":              SNR_RESTART_SYSCALL,
	"exit":                         SNR_EXIT,
	"fork":                         SNR_FORK,
	"read":                         SNR_READ,
	"write":                        SNR_WRITE,
	"open":                         SNR_OPEN,
	"close":                        SNR_CLOSE,
	"waitpid":                      SNR_WAITPID,
	"creat":                        SNR_CREAT,
	"link":                         SNR_LINK,
	"unlink":                       SNR_UNLINK,
	"execve":                       SNR_EXECVE,
	"chdir":                        SNR_CHDIR,
	"time":                         SNR_TIME,
	"mknod":                        SNR_MKNOD,
	"chmod":                        SNR_CHMOD,
	"lchown":                       SNR_LCHOWN,
	"break":                        SNR_BREAK,
	"oldstat":                      SNR_OLDSTAT,
	"lseek":                        SNR_LSEEK,
	"getpid":                       SNR_GETPID,
	"mount":                        SNR_MOUNT,
	"umount":                       SNR_UMOUNT,
	"setuid":                       SNR_SETUID,
	"getuid":                       SNR_GETUID,
	"stime":                        SNR_STIME,
	"ptrace":                       SNR_PTRACE,
	"alarm":                        SNR_ALARM,
	"oldfstat":                     SNR_OLDFSTAT,
	"pause":                        SNR_PAUSE,
	"utime":                        SNR_UTIME,
	"stty":                         SNR_STTY,
	"gtty":                         SNR_GTTY,
	"access":                       SNR_ACCESS,
	"nice":                         SNR_NICE,
	"ftime":                        SNR_FTIME,
	"sync":                         SNR_SYNC,
	"kill":                         SNR_KILL,
	"rename":                       SNR_RENAME,
	"mkdir":                        SNR_MKDIR,
	"rmdir":                        SNR_RMDIR,
	"dup":                          SNR_DUP,
	"pipe":                         SNR_PIPE,
	"times":                        SNR_TIMES,
	"prof":                         SNR_PROF,
	"brk":                          SNR_BRK,
	"setgid":                       SNR_SETGID,
	"getgid":                       SNR_GETGID,
	"signal":                       SNR_SIGNAL,
	"geteuid":                      SNR_GETEUID,
	"getegid":                      SNR_GETEGID,
	"acct":                         SNR_ACCT,
	"umount2":                      SNR_UMOUNT2,
	"lock":                         SNR_LOCK,
	"ioctl":                        SNR_IOCTL,
	"fcntl":                        SNR_FCNTL,
	"mpx":                          SNR_MPX,
	"setpgid":                      SNR_SETPGID,
	"ulimit":                       SNR_ULIMIT,
	"oldolduname":                  SNR_OLDOLDUNAME,
	"umask":                        SNR_UMASK,
	"chroot":                       SNR_CHROOT,
	"ustat":                        SNR_USTAT,
	"dup2":                         SNR_DUP2,
	"getppid":                      SNR_GETPPID,
	"getpgrp":                      SNR_GETPGRP,
	"setsid":                       SNR_SETSID,
	"sigaction":                    SNR_SIGACTION,
	"sgetmask":                     SNR_SGETMASK,
	"ssetmask":                     SNR_SSETMASK,
	"setreuid":                     SNR_SETREUID,
	"setregid":                     SNR_SETREGID,
	"sigsuspend":                   SNR_SIGSUSPEND,
	"sigpending":                   SNR_SIGPENDING,
	"sethostname":                  SNR_SETHOSTNAME,
	"setrlimit":                    SNR_SETRLIMIT,
	"getrlimit":                    SNR_GETRLIMIT,
	"getrusage":                    SNR_GETRUSAGE,
	"gettimeofday":                 SNR_GETTIMEOFDAY,
	"settimeofday":                 SNR_SETTIMEOFDAY,
	"getgroups":                    SNR_GETGROUPS,
	"setgroups":                    SNR_SETGROUPS,
	"select":                       SNR_SELECT,
	"symlink":                      SNR_SYMLINK,
	"oldlstat":                     SNR_OLDLSTAT,
	"readlink":                     SNR_READLINK,
	"uselib":                       SNR_USELIB,
	"swapon":                       SNR_SWAPON,
	"reboot":                       SNR_REBOOT,
	"readdir":                      SNR_READDIR,
	"mmap":                         SNR_MMAP,
	"munmap":                       SNR_MUNMAP,
	"truncate":                     SNR_TRUNCATE,
	"ftruncate":                    SNR_FTRUNCATE,
	"fchmod":                       SNR_FCHMOD,
	"fchown":                       SNR_FCHOWN,
	"getpriority":                  SNR_GETPRIORITY,
	"setpriority":                  SNR_SETPRIORITY,
	"profil":                       SNR_PROFIL,
	"statfs":                       SNR_STATFS,
	"fstatfs":                      SNR_FSTATFS,
	"ioperm":                       SNR_IOPERM,
	"socketcall":                   SNR_SOCKETCALL,
	"syslog":                       SNR_SYSLOG,
	"setitimer":                    SNR_SETITIMER,
	"getitimer":                    SNR_GETITIMER,
	"stat":                         SNR_STAT,
	"lstat":                        SNR_LSTAT,
	"fstat":                        SNR_FSTAT,
	"olduname":                     SNR_OLDUNAME,
	"iopl":                         SNR_IOPL,
	"vhangup":                      SNR_VHANGUP,
	"idle":                         SNR_IDLE,
	"vm86old":                      SNR_VM86OLD,
	"wait4":                        SNR_WAIT4,
	"swapoff":                      SNR_SWAPOFF,
	"sysinfo":                      SNR_SYSINFO,
	"ipc":                          SNR_IPC,
	"fsync":                        SNR_FSYNC,
	"sigreturn":                    SNR_SIGRETURN,
	"clone":                        SNR_CLONE,
	"setdomainname":                SNR_SETDOMAINNAME,
	"uname":                        SNR_UNAME,
	"modify_ldt":                   SNR_MODIFY_LDT,
	"adjtimex":                     SNR_ADJTIMEX,
	"mprotect":                     SNR_MPROTECT,
	"sigprocmask":                  SNR_SIGPROCMASK,
	"create_module":                SNR_CREATE_MODULE,
	"init_module":                  SNR_INIT_MODULE,
	"delete_module":                SNR_DELETE_MODULE,
	"get_kernel_syms":              SNR_GET_KERNEL_SYMS,
	"quotactl":                     SNR_QUOTACTL,
	"getpgid":                      SNR_GETPGID,
	"fchdir":                       SNR_FCHDIR,
	"bdflush":                      SNR_BDFLUSH,
	"sysfs":                        SNR_SYSFS,
	"personality":                  SNR_PERSONALITY,
	"afs_syscall":                  SNR_AFS_SYSCALL,
	"setfsuid":                     SNR_SETFSUID,
	"setfsgid":                     SNR_SETFSGID,
	"_llseek":                      SNR__LLSEEK,
	"getdents":                     SNR_GETDENTS,
	"_newselect":                   SNR__NEWSELECT,
	"flock":                        SNR_FLOCK,
	"msync":                        SNR_MSYNC,
	"readv":                        SNR_READV,
	"writev":                       SNR_WRITEV,
	"getsid":                       SNR_GETSID,
	"fdatasync":                    SNR_FDATASYNC,
	"_sysctl":                      SNR__SYSCTL,
	"mlock":                        SNR_MLOCK,
	"munlock":                      SNR_MUNLOCK,
	"mlockall":                     SNR_MLOCKALL,
	"munlockall":                   SNR_MUNLOCKALL,
	"sched_setparam":               SNR_SCHED_SETPARAM,
	"sched_getparam":               SNR_SCHED_GETPARAM,
	"sched_setscheduler":           SNR_SCHED_SETSCHEDULER,
	"sched_getscheduler":           SNR_SCHED_GETSCHEDULER,
	"sched_yield":                  SNR_SCHED_YIELD,
	"sched_get_priority_max":       SNR_SCHED_GET_PRIORITY_MAX,
	"sched_get_priority_min":       SNR_SCHED_GET_PRIORITY_MIN,
	"sched_rr_get_interval":        SNR_SCHED_RR_GET_INTERVAL,
	"nanosleep":                    SNR_NANOSLEEP,
	"mremap":                       SNR_MREMAP,
	"setresuid":                    SNR_SETRESUID,
	"getresuid":                    SNR_GETRESUID,
	"vm86":                         SNR_VM86,
	"query_module":                 SNR_QUERY_MODULE,
	"poll":                         SNR_POLL,
	"nfsservctl":                   SNR_NFSSERVCTL,
	"setresgid":                    SNR_SETRESGID,
	"getresgid":                    SNR_GETRESGID,
	"prctl":                        SNR_PRCTL,
	"rt_sigreturn":                 SNR_RT_SIGRETURN,
	"rt_sigaction":                 SNR_RT_SIGACTION,
	"rt_sigprocmask":               SNR_RT_SIGPROCMASK,
	"rt_sigpending":                SNR_RT_SIGPENDING,
	"rt_sigtimedwait":              SNR_RT_SIGTIMEDWAIT,
	"rt_sigqueueinfo":              SNR_RT_SIGQUEUEINFO,
	"rt_sigsuspend":                SNR_RT_SIGSUSPEND,
	"pread64":                      SNR_PREAD64,
	"pwrite64":                     SNR_PWRITE64,
	"chown":                        SNR_CHOWN,
	"getcwd":                       SNR_GETCWD,
	"capget":                       SNR_CAPGET,
	"capset":                       SNR_CAPSET,
	"sigaltstack":                  SNR_SIGALTSTACK,
	"sendfile":                     SNR_SENDFILE,
	"getpmsg":                      SNR_GETPMSG,
	"putpmsg":                      SNR_PUTPMSG,
	"vfork":                        SNR_VFORK,
	"ugetrlimit":                   SNR_UGETRLIMIT,
	"mmap2":                        SNR_MMAP2,
	"truncate64":                   SNR_TRUNCATE64,
	"ftruncate64":                  SNR_FTRUNCATE64,
	"stat64":                       SNR_STAT64,
	"lstat64":                      SNR_LSTAT64,
	"fstat64":                      SNR_FSTAT64,
	"lchown32":                     SNR_LCHOWN32,
	"getuid32":                     SNR_GETUID32,
	"getgid32":                     SNR_GETGID32,
	"geteuid32":                    SNR_GETEUID32,
	"getegid32":                    SNR_GETEGID32,
	"setreuid32":                   SNR_SETREUID32,
	"setregid32":                   SNR_SETREGID32,
	"getgroups32":                  SNR_GETGROUPS32,
	"setgroups32":                  SNR_SETGROUPS32,
	"fchown32":                     SNR_FCHOWN32,
	"setresuid32":                  SNR_SETRESUID32,
	"getresuid32":                  SNR_GETRESUID32,
	"setresgid32":                  SNR_SETRESGID32,
	"getresgid32":                  SNR_GETRESGID32,
	"chown32":                      SNR_CHOWN32,
	"setuid32":                     SNR_SETUID32,
	"setgid32":                     SNR_SETGID32,
	"setfsuid32":                   SNR_SETFSUID32,
	"setfsgid32":                   SNR_SETFSGID32,
	"pivot_root":                   SNR_PIVOT_ROOT,
	"mincore":                      SNR_MINCORE,
	"madvise":                      SNR_MADVISE,
	"getdents64":                   SNR_GETDENTS64,
	"fcntl64":                      SNR_FCNTL64,
	"gettid":                       SNR_GETTID,
	"readahead":                    SNR_READAHEAD,
	"setxattr":                     SNR_SETXATTR,
	"lsetxattr":                    SNR_LSETXATTR,
	"fsetxattr":                    SNR_FSETXATTR,
	"getxattr":                     SNR_GETXATTR,
	"lgetxattr":                    SNR_LGETXATTR,
	"fgetxattr":                    SNR_FGETXATTR,
	"listxattr":                    SNR_LISTXATTR,
	"llistxattr":                   SNR_LLISTXATTR,
	"flistxattr":                   SNR_FLISTXATTR,
	"removexattr":                  SNR_REMOVEXATTR,
	"lremovexattr":                 SNR_LREMOVEXATTR,
	"fremovexattr":                 SNR_FREMOVEXATTR,
	"tkill":                        SNR_TKILL,
	"sendfile64":                   SNR_SENDFILE64,
	"futex":                        SNR_FUTEX,
	"sched_setaffinity":            SNR_SCHED_SETAFFINITY,
	"sched_getaffinity":            SNR_SCHED_GETAFFINITY,
	"set_thread_area":              SNR_SET_THREAD_AREA,
	"get_thread_area":              SNR_GET_THREAD_AREA,
	"io_setup":                     SNR_IO_SETUP,
	"io_destroy":                   SNR_IO_DESTROY,
	"io_getevents":                 SNR_IO_GETEVENTS,
	"io_submit":                    SNR_IO_SUBMIT,
	"io_cancel":                    SNR_IO_CANCEL,
	"fadvise64":                    SNR_FADVISE64,
	"exit_group":                   SNR_EXIT_GROUP,
	"lookup_dcookie":               SNR_LOOKUP_DCOOKIE,
	"epoll_create":                 SNR_EPOLL_CREATE,
	"epoll_ctl":                    SNR_EPOLL_CTL,
	"epoll_wait":                   SNR_EPOLL_WAIT,
	"remap_file_pages":             SNR_REMAP_FILE_PAGES,
	"set_tid_address":              SNR_SET_TID_ADDRESS,
	"timer_create":                 SNR_TIMER_CREATE,
	"timer_settime":                SNR_TIMER_SETTIME,
	"timer_gettime":                SNR_TIMER_GETTIME,
	"timer_getoverrun":             SNR_TIMER_GETOVERRUN,
	"timer_delete":                 SNR_TIMER_DELETE,
	"clock_settime":                SNR_CLOCK_SETTIME,
	"clock_gettime":                SNR_CLOCK_GETTIME,
	"clock_getres":                 SNR_CLOCK_GETRES,
	"clock_nanosleep":              SNR_CLOCK_NANOSLEEP,
	"statfs64":                     SNR_STATFS64,
	"fstatfs64":                    SNR_FSTATFS64,
	"tgkill":                       SNR_TGKILL,
	"utimes":                       SNR_UTIMES,
	"fadvise64_64":                 SNR_FADVISE64_64,
	"vserver":                      SNR_VSERVER,
	"mbind":                        SNR_MBIND,
	"get_mempolicy":                SNR_GET_MEMPOLICY,
	"set_mempolicy":                SNR_SET_MEMPOLICY,
	"mq_open":                      SNR_MQ_OPEN,
	"mq_unlink":                    SNR_MQ_UNLINK,
	"mq_timedsend":                 SNR_MQ_TIMEDSEND,
	"mq_timedreceive":              SNR_MQ_TIMEDRECEIVE,
	"mq_notify":                    SNR_MQ_NOTIFY,
	"mq_getsetattr":                SNR_MQ_GETSETATTR,
	"kexec_load":                   SNR_KEXEC_LOAD,
	"waitid":                       SNR_WAITID,
	"add_key":                      SNR_ADD_KEY,
	"request_key":                  SNR_REQUEST_KEY,
	"keyctl":                       SNR_KEYCTL,
	"ioprio_set":                   SNR_IOPRIO_SET,
	"ioprio_get":                   SNR_IOPRIO_GET,
	"inotify_init":                 SNR_INOTIFY_INIT,
	"inotify_add_watch":            SNR_INOTIFY_ADD_WATCH,
	"inotify_rm_watch":             SNR_INOTIFY_RM_WATCH,
	"migrate_pages":                SNR_MIGRATE_PAGES,
	"openat":                       SNR_OPENAT,
	"mkdirat":                      SNR_MKDIRAT,
	"mknodat":                      SNR_MKNODAT,
	"fchownat":                     SNR_FCHOWNAT,
	"futimesat":                    SNR_FUTIMESAT,
	"fstatat64":                    SNR_FSTATAT64,
	"unlinkat":                     SNR_UNLINKAT,
	"renameat":                     SNR_RENAMEAT,
	"linkat":                       SNR_LINKAT,
	"symlinkat":                    SNR_SYMLINKAT,
	"readlinkat":                   SNR_READLINKAT,
	"fchmodat":                     SNR_FCHMODAT,
	"faccessat":                    SNR_FACCESSAT,
	"pselect6":                     SNR_PSELECT6,
	"ppoll":                        SNR_PPOLL,
	"unshare":                      SNR_UNSHARE,
	"set_robust_list":              SNR_SET_ROBUST_LIST,
	"get_robust_list":              SNR_GET_ROBUST_LIST,
	"splice":                       SNR_SPLICE,
	"sync_file_range":              SNR_SYNC_FILE_RANGE,
	"tee":                          SNR_TEE,
	"vmsplice":                     SNR_VMSPLICE,
	"move_pages":                   SNR_MOVE_PAGES,
	"getcpu":                       SNR_GETCPU,
	"epoll_pwait":                  SNR_EPOLL_PWAIT,
	"utimensat":                    SNR_UTIMENSAT,
	"signalfd":                     SNR_SIGNALFD,
	"timerfd_create":               SNR_TIMERFD_CREATE,
	"eventfd":                      SNR_EVENTFD,
	"fallocate":                    SNR_FALLOCATE,
	"timerfd_settime":              SNR_TIMERFD_SETTIME,
	"timerfd_gettime":              SNR_TIMERFD_GETTIME,
	"signalfd4":                    SNR_SIGNALFD4,
	"eventfd2":                     SNR_EVENTFD2,
	"epoll_create1":                SNR_EPOLL_CREATE1,
	"dup3":                         SNR_DUP3,
	"pipe2":                        SNR_PIPE2,
	"inotify_init1":                SNR_INOTIFY_INIT1,
	"preadv":                       SNR_PREADV,
	"pwritev":                      SNR_PWRITEV,
	"rt_tgsigqueueinfo":            SNR_RT_TGSIGQUEUEINFO,
	"perf_event_open":              SNR_PERF_EVENT_OPEN,
	"recvmmsg":                     SNR_RECVMMSG,
	"fanotify_init":                SNR_FANOTIFY_INIT,
	"fanotify_mark":                SNR_FANOTIFY_MARK,
	"prlimit64":                    SNR_PRLIMIT64,
	"name_to_handle_at":            SNR_NAME_TO_HANDLE_AT,
	"open_by_handle_at":            SNR_OPEN_BY_HANDLE_AT,
	"clock_adjtime":                SNR_CLOCK_ADJTIME,
	"syncfs":                       SNR_SYNCFS,
	"sendmmsg":                     SNR_SENDMMSG,
	"setns":                        SNR_SETNS,
	"process_vm_readv":             SNR_PROCESS_VM_READV,
	"process_vm_writev":            SNR_PROCESS_VM_WRITEV,
	"kcmp":                         SNR_KCMP,
	"finit_module":                 SNR_FINIT_MODULE,
	"sched_setattr":                SNR_SCHED_SETATTR,
	"sched_getattr":                SNR_SCHED_GETATTR,
	"renameat2":                    SNR_RENAMEAT2,
	"seccomp":                      SNR_SECCOMP,
	"getrandom":                    SNR_GETRANDOM,
	"memfd_create":                 SNR_MEMFD_CREATE,
	"bpf":                          SNR_BPF,
	"execveat":                     SNR_EXECVEAT,
	"socket":                       SNR_SOCKET,
	"socketpair":                   SNR_SOCKETPAIR,
	"bind":                         SNR_BIND,
	"connect":                      SNR_CONNECT,
	"listen":                       SNR_LISTEN,
	"accept4":                      SNR_ACCEPT4,
	"getsockopt":                   SNR_GETSOCKOPT,
	"setsockopt":                   SNR_SETSOCKOPT,
	"getsockname":                  SNR_GETSOCKNAME,
	"getpeername":                  SNR_GETPEERNAME,
	"sendto":                       SNR_SENDTO,
	"sendmsg":                      SNR_SENDMSG,
	"recvfrom":                     SNR_RECVFROM,
	"recvmsg":                      SNR_RECVMSG,
	"shutdown":                     SNR_SHUTDOWN,
	"userfaultfd":                  SNR_USERFAULTFD,
	"membarrier":                   SNR_MEMBARRIER,
	"mlock2":                       SNR_MLOCK2,
	"copy_file_range":              SNR_COPY_FILE_RANGE,
	"preadv2":                      SNR_PREADV2,
	"pwritev2":                     SNR_PWRITEV2,
	"pkey_mprotect":                SNR_PKEY_MPROTECT,
	"pkey_alloc":                   SNR_PKEY_ALLOC,
	"pkey_free":                    SNR_PKEY_FREE,
	"statx":                        SNR_STATX,
	"arch_prctl":                   SNR_ARCH_PRCTL,
	"io_pgetevents":                SNR_IO_PGETEVENTS,
	"rseq":                         SNR_RSEQ,
	"semget":                       SNR_SEMGET,
	"semctl":                       SNR_SEMCTL,
	"shmget":                       SNR_SHMGET,
	"shmctl":                       SNR_SHMCTL,
	"shmat":                        SNR_SHMAT,
	"shmdt":                        SNR_SHMDT,
	"msgget":                       SNR_MSGGET,
	"msgsnd":                       SNR_MSGSND,
	"msgrcv":                       SNR_MSGRCV,
	"msgctl":                       SNR_MSGCTL,
	"clock_gettime64":              SNR_CLOCK_GETTIME64,
	"clock_settime64":              SNR_CLOCK_SETTIME64,
	"clock_adjtime64":              SNR_CLOCK_ADJTIME64,
	"clock_getres_time64":          SNR_CLOCK_GETRES_TIME64,
	"clock_nanosleep_time64":       SNR_CLOCK_NANOSLEEP_TIME64,
	"timer_gettime64":              SNR_TIMER_GETTIME64,
	"timer_settime64":              SNR_TIMER_SETTIME64,
	"timerfd_gettime64":            SNR_TIMERFD_GETTIME64,
	"timerfd_settime64":            SNR_TIMERFD_SETTIME64,
	"utimensat_time64":             SNR_UTIMENSAT_TIME64,
	"pselect6_time64":              SNR_PSELECT6_TIME64,
	"ppoll_time64":                 SNR_PPOLL_TIME64,
	"io_pgetevents_time64":         SNR_IO_PGETEVENTS_TIME64,
	"recvmmsg_time64":              SNR_RECVMMSG_TIME64,
	"mq_timedsend_time64":          SNR_MQ_TIMEDSEND_TIME64,
	"mq_timedreceive_time64":       SNR_MQ_TIMEDRECEIVE_TIME64,
	"semtimedop_time64":            SNR_SEMTIMEDOP_TIME64,
	"rt_sigtimedwait_time64":       SNR_RT_SIGTIMEDWAIT_TIME64,
	"futex_time64":                 SNR_FUTEX_TIME64,
	"sched_rr_get_interval_time64": SNR_SCHED_RR_GET_INTERVAL_TIME64,
	"pidfd_send_signal":            SNR_PIDFD_SEND_SIGNAL,
	"io_uring_setup":               SNR_IO_URING_SETUP,
	"io_uring_enter":               SNR_IO_URING_ENTER,
	"io_uring_register":            SNR_IO_URING_REGISTER,
	"open_tree":                    SNR_OPEN_TREE,
	"move_mount":                   SNR_MOVE_MOUNT,
	"fsopen":                       SNR_FSOPEN,
	"fsconfig":                     SNR_FSCONFIG,
	"fsmount":                      SNR_FSMOUNT,
	"fspick":                       SNR_FSPICK,
	"pidfd_open":                   SNR_PIDFD_OPEN,
	"clone3":                       SNR_CLONE3,
	"close_range":                  SNR_CLOSE_RANGE,
	"openat2":                      SNR_OPENAT2,
	"pidfd_getfd":                  SNR_PIDFD_GETFD,
	"faccessat2":                   SNR_FACCESSAT2,
	"process_madvise":              SNR_PROCESS_MADVISE,
	"epoll_pwait2":                 SNR_EPOLL_PWAIT2,
	"mount_setattr":                SNR_MOUNT_SETATTR,
	"quotactl_fd":                  SNR_QUOTACTL_FD,
	"landlock_create_ruleset":      SNR_LANDLOCK_CREATE_RULESET,
	"landlock_add_rule":            SNR_LANDLOCK_ADD_RULE,
	"landlock_restrict_self":       SNR_LANDLOCK_RESTRICT_SELF,
	"memfd_secret":                 SNR_MEMFD_SECRET,
	"process_mrelease":             SNR_PROCESS_MRELEASE,
	"futex_waitv":                  SNR_FUTEX_WAITV,
	"set_mempolicy_home_node":      SNR_SET_MEMPOLICY_HOME_NODE,
	"cachestat":                    SNR_CACHESTAT,
	"fchmodat2":                    SNR_FCHMODAT2,
	"map_shadow_stack":             SNR_MAP_SHADOW_STACK,
	"futex_wake":                   SNR_FUTEX_WAKE,
	"futex_wait":                   SNR_FUTEX_WAIT,
	"futex_requeue":                SNR_FUTEX_REQUEUE,
	"statmount":                    SNR_STATMOUNT,
	"listmount":                    SNR_LISTMOUNT,
	"lsm_get_self_attr":            SNR_LSM_GET_SELF_ATTR,
	"lsm_set_self_attr":            SNR_LSM_SET_SELF_ATTR,
	"lsm_list_modules":             SNR_LSM_LIST_MODULES,
	"mseal":                        SNR_MSEAL,
}

const (
	SYS_NAME_TO_HANDLE_AT            = 341
	SYS_OPEN_BY_HANDLE_AT            = 342
	SYS_CLOCK_ADJTIME                = 343
	SYS_SYNCFS                       = 344
	SYS_SENDMMSG                     = 345
	SYS_SETNS                        = 346
	SYS_PROCESS_VM_READV             = 347
	SYS_PROCESS_VM_WRITEV            = 348
	SYS_KCMP                         = 349
	SYS_FINIT_MODULE                 = 350
	SYS_SCHED_SETATTR                = 351
	SYS_SCHED_GETATTR                = 352
	SYS_RENAMEAT2                    = 353
	SYS_SECCOMP                      = 354
	SYS_GETRANDOM                    = 355
	SYS_MEMFD_CREATE                 = 356
	SYS_BPF                          = 357
	SYS_EXECVEAT                     = 358
	SYS_SOCKET                       = 359
	SYS_SOCKETPAIR                   = 360
	SYS_BIND                         = 361
	SYS_CONNECT                      = 362
	SYS_LISTEN                       = 363
	SYS_ACCEPT4                      = 364
	SYS_GETSOCKOPT                   = 365
	SYS_SETSOCKOPT                   = 366
	SYS_GETSOCKNAME                  = 367
	SYS_GETPEERNAME                  = 368
	SYS_SENDTO                       = 369
	SYS_SENDMSG                      = 370
	SYS_RECVFROM                     = 371
	SYS_RECVMSG                      = 372
	SYS_SHUTDOWN                     = 373
	SYS_USERFAULTFD                  = 374
	SYS_MEMBARRIER                   = 375
	SYS_MLOCK2                       = 376
	SYS_COPY_FILE_RANGE              = 377
	SYS_PREADV2                      = 378
	SYS_PWRITEV2                     = 379
	SYS_PKEY_MPROTECT                = 380
	SYS_PKEY_ALLOC                   = 381
	SYS_PKEY_FREE                    = 382
	SYS_STATX                        = 383
	SYS_ARCH_PRCTL                   = 384
	SYS_IO_PGETEVENTS                = 385
	SYS_RSEQ                         = 386
	SYS_SEMGET                       = 393
	SYS_SEMCTL                       = 394
	SYS_SHMGET                       = 395
	SYS_SHMCTL                       = 396
	SYS_SHMAT                        = 397
	SYS_SHMDT                        = 398
	SYS_MSGGET                       = 399
	SYS_MSGSND                       = 400
	SYS_MSGRCV                       = 401
	SYS_MSGCTL                       = 402
	SYS_CLOCK_GETTIME64              = 403
	SYS_CLOCK_SETTIME64              = 404
	SYS_CLOCK_ADJTIME64              = 405
	SYS_CLOCK_GETRES_TIME64          = 406
	SYS_CLOCK_NANOSLEEP_TIME64       = 407
	SYS_TIMER_GETTIME64              = 408
	SYS_TIMER_SETTIME64              = 409
	SYS_TIMERFD_GETTIME64            = 410
	SYS_TIMERFD_SETTIME64            = 411
	SYS_UTIMENSAT_TIME64             = 412
	SYS_PSELECT6_TIME64              = 413
	SYS_PPOLL_TIME64                 = 414
	SYS_IO_PGETEVENTS_TIME64         = 416
	SYS_RECVMMSG_TIME64              = 417
	SYS_MQ_TIMEDSEND_TIME64          = 418
	SYS_MQ_TIMEDRECEIVE_TIME64       = 419
	SYS_SEMTIMEDOP_TIME64            = 420
	SYS_RT_SIGTIMEDWAIT_TIME64       = 421
	SYS_FUTEX_TIME64                 = 422
	SYS_SCHED_RR_GET_INTERVAL_TIME64 = 423
	SYS_PIDFD_SEND_SIGNAL            = 424
	SYS_IO_URING_SETUP               = 425
	SYS_IO_URING_ENTER               = 426
	SYS_IO_URING_REGISTER            = 427
	SYS_OPEN_TREE                    = 428
	SYS_MOVE_MOUNT                   = 429
	SYS_FSOPEN                       = 430
	SYS_FSCONFIG                     = 431
	SYS_FSMOUNT                      = 432
	SYS_FSPICK                       = 433
	SYS_PIDFD_OPEN                   = 434
	SYS_CLONE3                       = 435
	SYS_CLOSE_RANGE                  = 436
	SYS_OPENAT2                      = 437
	SYS_PIDFD_GETFD                  = 438
	SYS_FACCESSAT2                   = 439
	SYS_PROCESS_MADVISE              = 440
	SYS_EPOLL_PWAIT2                 = 441
	SYS_MOUNT_SETATTR                = 442
	SYS_QUOTACTL_FD                  = 443
	SYS_LANDLOCK_CREATE_RULESET      = 444
	SYS_LANDLOCK_ADD_RULE            = 445
	SYS_LANDLOCK_RESTRICT_SELF       = 446
	SYS_MEMFD_SECRET                 = 447
	SYS_PROCESS_MRELEASE             = 448
	SYS_FUTEX_WAITV                  = 449
	SYS_SET_MEMPOLICY_HOME_NODE      = 450
	SYS_CACHESTAT                    = 451
	SYS_FCHMODAT2                    = 452
	SYS_MAP_SHADOW_STACK             = 453
	SYS_FUTEX_WAKE                   = 454
	SYS_FUTEX_WAIT                   = 455
	SYS_FUTEX_REQUEUE                = 456
	SYS_STATMOUNT                    = 457
	SYS_LISTMOUNT                    = 458
	SYS_LSM_GET_SELF_ATTR            = 459
	SYS_LSM_SET_SELF_ATTR            = 460
	SYS_LSM_LIST_MODULES             = 461
	SYS_MSEAL                        = 462
)

const (
	SNR_RESTART_SYSCALL              ScmpSyscall = SYS_RESTART_SYSCALL
	SNR_EXIT                         ScmpSyscall = SYS_EXIT
	SNR_FORK                         ScmpSyscall = SYS_FORK
	SNR_READ                         ScmpSyscall = SYS_READ
	SNR_WRITE                        ScmpSyscall = SYS_WRITE
	SNR_OPEN                         ScmpSyscall = SYS_OPEN
	SNR_CLOSE                        ScmpSyscall = SYS_CLOSE
	SNR_WAITPID                      ScmpSyscall = SYS_WAITPID
	SNR_CREAT                        ScmpSyscall = SYS_CREAT
	SNR_LINK                         ScmpSyscall = SYS_LINK
	SNR_UNLINK                       ScmpSyscall = SYS_UNLINK
	SNR_EXECVE                       ScmpSyscall = SYS_EXECVE
	SNR_CHDIR                        ScmpSyscall = SYS_CHDIR
	SNR_TIME                         ScmpSyscall = SYS_TIME
	SNR_MKNOD                        ScmpSyscall = SYS_MKNOD
	SNR_CHMOD                        ScmpSyscall = SYS_CHMOD
	SNR_LCHOWN                       ScmpSyscall = SYS_LCHOWN
	SNR_BREAK                        ScmpSyscall = SYS_BREAK
	SNR_OLDSTAT                      ScmpSyscall = SYS_OLDSTAT
	SNR_LSEEK                        ScmpSyscall = SYS_LSEEK
	SNR_GETPID                       ScmpSyscall = SYS_GETPID
	SNR_MOUNT                        ScmpSyscall = SYS_MOUNT
	SNR_UMOUNT                       ScmpSyscall = SYS_UMOUNT
	SNR_SETUID                       ScmpSyscall = SYS_SETUID
	SNR_GETUID                       ScmpSyscall = SYS_GETUID
	SNR_STIME                        ScmpSyscall = SYS_STIME
	SNR_PTRACE                       ScmpSyscall = SYS_PTRACE
	SNR_ALARM                        ScmpSyscall = SYS_ALARM
	SNR_OLDFSTAT                     ScmpSyscall = SYS_OLDFSTAT
	SNR_PAUSE                        ScmpSyscall = SYS_PAUSE
	SNR_UTIME                        ScmpSyscall = SYS_UTIME
	SNR_STTY                         ScmpSyscall = SYS_STTY
	SNR_GTTY                         ScmpSyscall = SYS_GTTY
	SNR_ACCESS                       ScmpSyscall = SYS_ACCESS
	SNR_NICE                         ScmpSyscall = SYS_NICE
	SNR_FTIME                        ScmpSyscall = SYS_FTIME
	SNR_SYNC                         ScmpSyscall = SYS_SYNC
	SNR_KILL                         ScmpSyscall = SYS_KILL
	SNR_RENAME                       ScmpSyscall = SYS_RENAME
	SNR_MKDIR                        ScmpSyscall = SYS_MKDIR
	SNR_RMDIR                        ScmpSyscall = SYS_RMDIR
	SNR_DUP                          ScmpSyscall = SYS_DUP
	SNR_PIPE                         ScmpSyscall = SYS_PIPE
	SNR_TIMES                        ScmpSyscall = SYS_TIMES
	SNR_PROF                         ScmpSyscall = SYS_PROF
	SNR_BRK                          ScmpSyscall = SYS_BRK
	SNR_SETGID                       ScmpSyscall = SYS_SETGID
	SNR_GETGID                       ScmpSyscall = SYS_GETGID
	SNR_SIGNAL                       ScmpSyscall = SYS_SIGNAL
	SNR_GETEUID                      ScmpSyscall = SYS_GETEUID
	SNR_GETEGID                      ScmpSyscall = SYS_GETEGID
	SNR_ACCT                         ScmpSyscall = SYS_ACCT
	SNR_UMOUNT2                      ScmpSyscall = SYS_UMOUNT2
	SNR_LOCK                         ScmpSyscall = SYS_LOCK
	SNR_IOCTL                        ScmpSyscall = SYS_IOCTL
	SNR_FCNTL                        ScmpSyscall = SYS_FCNTL
	SNR_MPX                          ScmpSyscall = SYS_MPX
	SNR_SETPGID                      ScmpSyscall = SYS_SETPGID
	SNR_ULIMIT                       ScmpSyscall = SYS_ULIMIT
	SNR_OLDOLDUNAME                  ScmpSyscall = SYS_OLDOLDUNAME
	SNR_UMASK                        ScmpSyscall = SYS_UMASK
	SNR_CHROOT                       ScmpSyscall = SYS_CHROOT
	SNR_USTAT                        ScmpSyscall = SYS_USTAT
	SNR_DUP2                         ScmpSyscall = SYS_DUP2
	SNR_GETPPID                      ScmpSyscall = SYS_GETPPID
	SNR_GETPGRP                      ScmpSyscall = SYS_GETPGRP
	SNR_SETSID                       ScmpSyscall = SYS_SETSID
	SNR_SIGACTION                    ScmpSyscall = SYS_SIGACTION
	SNR_SGETMASK                     ScmpSyscall = SYS_SGETMASK
	SNR_SSETMASK                     ScmpSyscall = SYS_SSETMASK
	SNR_SETREUID                     ScmpSyscall = SYS_SETREUID
	SNR_SETREGID                     ScmpSyscall = SYS_SETREGID
	SNR_SIGSUSPEND                   ScmpSyscall = SYS_SIGSUSPEND
	SNR_SIGPENDING                   ScmpSyscall = SYS_SIGPENDING
	SNR_SETHOSTNAME                  ScmpSyscall = SYS_SETHOSTNAME
	SNR_SETRLIMIT                    ScmpSyscall = SYS_SETRLIMIT
	SNR_GETRLIMIT                    ScmpSyscall = SYS_GETRLIMIT
	SNR_GETRUSAGE                    ScmpSyscall = SYS_GETRUSAGE
	SNR_GETTIMEOFDAY                 ScmpSyscall = SYS_GETTIMEOFDAY
	SNR_SETTIMEOFDAY                 ScmpSyscall = SYS_SETTIMEOFDAY
	SNR_GETGROUPS                    ScmpSyscall = SYS_GETGROUPS
	SNR_SETGROUPS                    ScmpSyscall = SYS_SETGROUPS
	SNR_SELECT                       ScmpSyscall = SYS_SELECT
	SNR_SYMLINK                      ScmpSyscall = SYS_SYMLINK
	SNR_OLDLSTAT                     ScmpSyscall = SYS_OLDLSTAT
	SNR_READLINK                     ScmpSyscall = SYS_READLINK
	SNR_USELIB                       ScmpSyscall = SYS_USELIB
	SNR_SWAPON                       ScmpSyscall = SYS_SWAPON
	SNR_REBOOT                       ScmpSyscall = SYS_REBOOT
	SNR_READDIR                      ScmpSyscall = SYS_READDIR
	SNR_MMAP                         ScmpSyscall = SYS_MMAP
	SNR_MUNMAP                       ScmpSyscall = SYS_MUNMAP
	SNR_TRUNCATE                     ScmpSyscall = SYS_TRUNCATE
	SNR_FTRUNCATE                    ScmpSyscall = SYS_FTRUNCATE
	SNR_FCHMOD                       ScmpSyscall = SYS_FCHMOD
	SNR_FCHOWN                       ScmpSyscall = SYS_FCHOWN
	SNR_GETPRIORITY                  ScmpSyscall = SYS_GETPRIORITY
	SNR_SETPRIORITY                  ScmpSyscall = SYS_SETPRIORITY
	SNR_PROFIL                       ScmpSyscall = SYS_PROFIL
	SNR_STATFS                       ScmpSyscall = SYS_STATFS
	SNR_FSTATFS                      ScmpSyscall = SYS_FSTATFS
	SNR_IOPERM                       ScmpSyscall = SYS_IOPERM
	SNR_SOCKETCALL                   ScmpSyscall = SYS_SOCKETCALL
	SNR_SYSLOG                       ScmpSyscall = SYS_SYSLOG
	SNR_SETITIMER                    ScmpSyscall = SYS_SETITIMER
	SNR_GETITIMER                    ScmpSyscall = SYS_GETITIMER
	SNR_STAT                         ScmpSyscall = SYS_STAT
	SNR_LSTAT                        ScmpSyscall = SYS_LSTAT
	SNR_FSTAT                        ScmpSyscall = SYS_FSTAT
	SNR_OLDUNAME                     ScmpSyscall = SYS_OLDUNAME
	SNR_IOPL                         ScmpSyscall = SYS_IOPL
	SNR_VHANGUP                      ScmpSyscall = SYS_VHANGUP
	SNR_IDLE                         ScmpSyscall = SYS_IDLE
	SNR_VM86OLD                      ScmpSyscall = SYS_VM86OLD
	SNR_WAIT4                        ScmpSyscall = SYS_WAIT4
	SNR_SWAPOFF                      ScmpSyscall = SYS_SWAPOFF
	SNR_SYSINFO                      ScmpSyscall = SYS_SYSINFO
	SNR_IPC                          ScmpSyscall = SYS_IPC
	SNR_FSYNC                        ScmpSyscall = SYS_FSYNC
	SNR_SIGRETURN                    ScmpSyscall = SYS_SIGRETURN
	SNR_CLONE                        ScmpSyscall = SYS_CLONE
	SNR_SETDOMAINNAME                ScmpSyscall = SYS_SETDOMAINNAME
	SNR_UNAME                        ScmpSyscall = SYS_UNAME
	SNR_MODIFY_LDT                   ScmpSyscall = SYS_MODIFY_LDT
	SNR_ADJTIMEX                     ScmpSyscall = SYS_ADJTIMEX
	SNR_MPROTECT                     ScmpSyscall = SYS_MPROTECT
	SNR_SIGPROCMASK                  ScmpSyscall = SYS_SIGPROCMASK
	SNR_CREATE_MODULE                ScmpSyscall = SYS_CREATE_MODULE
	SNR_INIT_MODULE                  ScmpSyscall = SYS_INIT_MODULE
	SNR_DELETE_MODULE                ScmpSyscall = SYS_DELETE_MODULE
	SNR_GET_KERNEL_SYMS              ScmpSyscall = SYS_GET_KERNEL_SYMS
	SNR_QUOTACTL                     ScmpSyscall = SYS_QUOTACTL
	SNR_GETPGID                      ScmpSyscall = SYS_GETPGID
	SNR_FCHDIR                       ScmpSyscall = SYS_FCHDIR
	SNR_BDFLUSH                      ScmpSyscall = SYS_BDFLUSH
	SNR_SYSFS                        ScmpSyscall = SYS_SYSFS
	SNR_PERSONALITY                  ScmpSyscall = SYS_PERSONALITY
	SNR_AFS_SYSCALL                  ScmpSyscall = SYS_AFS_SYSCALL
	SNR_SETFSUID                     ScmpSyscall = SYS_SETFSUID
	SNR_SETFSGID                     ScmpSyscall = SYS_SETFSGID
	SNR__LLSEEK                      ScmpSyscall = SYS__LLSEEK
	SNR_GETDENTS                     ScmpSyscall = SYS_GETDENTS
	SNR__NEWSELECT                   ScmpSyscall = SYS__NEWSELECT
	SNR_FLOCK                        ScmpSyscall = SYS_FLOCK
	SNR_MSYNC                        ScmpSyscall = SYS_MSYNC
	SNR_READV                        ScmpSyscall = SYS_READV
	SNR_WRITEV                       ScmpSyscall = SYS_WRITEV
	SNR_GETSID                       ScmpSyscall = SYS_GETSID
	SNR_FDATASYNC                    ScmpSyscall = SYS_FDATASYNC
	SNR__SYSCTL                      ScmpSyscall = SYS__SYSCTL
	SNR_MLOCK                        ScmpSyscall = SYS_MLOCK
	SNR_MUNLOCK                      ScmpSyscall = SYS_MUNLOCK
	SNR_MLOCKALL                     ScmpSyscall = SYS_MLOCKALL
	SNR_MUNLOCKALL                   ScmpSyscall = SYS_MUNLOCKALL
	SNR_SCHED_SETPARAM               ScmpSyscall = SYS_SCHED_SETPARAM
	SNR_SCHED_GETPARAM               ScmpSyscall = SYS_SCHED_GETPARAM
	SNR_SCHED_SETSCHEDULER           ScmpSyscall = SYS_SCHED_SETSCHEDULER
	SNR_SCHED_GETSCHEDULER           ScmpSyscall = SYS_SCHED_GETSCHEDULER
	SNR_SCHED_YIELD                  ScmpSyscall = SYS_SCHED_YIELD
	SNR_SCHED_GET_PRIORITY_MAX       ScmpSyscall = SYS_SCHED_GET_PRIORITY_MAX
	SNR_SCHED_GET_PRIORITY_MIN       ScmpSyscall = SYS_SCHED_GET_PRIORITY_MIN
	SNR_SCHED_RR_GET_INTERVAL        ScmpSyscall = SYS_SCHED_RR_GET_INTERVAL
	SNR_NANOSLEEP                    ScmpSyscall = SYS_NANOSLEEP
	SNR_MREMAP                       ScmpSyscall = SYS_MREMAP
	SNR_SETRESUID                    ScmpSyscall = SYS_SETRESUID
	SNR_GETRESUID                    ScmpSyscall = SYS_GETRESUID
	SNR_VM86                         ScmpSyscall = SYS_VM86
	SNR_QUERY_MODULE                 ScmpSyscall = SYS_QUERY_MODULE
	SNR_POLL                         ScmpSyscall = SYS_POLL
	SNR_NFSSERVCTL                   ScmpSyscall = SYS_NFSSERVCTL
	SNR_SETRESGID                    ScmpSyscall = SYS_SETRESGID
	SNR_GETRESGID                    ScmpSyscall = SYS_GETRESGID
	SNR_PRCTL                        ScmpSyscall = SYS_PRCTL
	SNR_RT_SIGRETURN                 ScmpSyscall = SYS_RT_SIGRETURN
	SNR_RT_SIGACTION                 ScmpSyscall = SYS_RT_SIGACTION
	SNR_RT_SIGPROCMASK               ScmpSyscall = SYS_RT_SIGPROCMASK
	SNR_RT_SIGPENDING                ScmpSyscall = SYS_RT_SIGPENDING
	SNR_RT_SIGTIMEDWAIT              ScmpSyscall = SYS_RT_SIGTIMEDWAIT
	SNR_RT_SIGQUEUEINFO              ScmpSyscall = SYS_RT_SIGQUEUEINFO
	SNR_RT_SIGSUSPEND                ScmpSyscall = SYS_RT_SIGSUSPEND
	SNR_PREAD64                      ScmpSyscall = SYS_PREAD64
	SNR_PWRITE64                     ScmpSyscall = SYS_PWRITE64
	SNR_CHOWN                        ScmpSyscall = SYS_CHOWN
	SNR_GETCWD                       ScmpSyscall = SYS_GETCWD
	SNR_CAPGET                       ScmpSyscall = SYS_CAPGET
	SNR_CAPSET                       ScmpSyscall = SYS_CAPSET
	SNR_SIGALTSTACK                  ScmpSyscall = SYS_SIGALTSTACK
	SNR_SENDFILE                     ScmpSyscall = SYS_SENDFILE
	SNR_GETPMSG                      ScmpSyscall = SYS_GETPMSG
	SNR_PUTPMSG                      ScmpSyscall = SYS_PUTPMSG
	SNR_VFORK                        ScmpSyscall = SYS_VFORK
	SNR_UGETRLIMIT                   ScmpSyscall = SYS_UGETRLIMIT
	SNR_MMAP2                        ScmpSyscall = SYS_MMAP2
	SNR_TRUNCATE64                   ScmpSyscall = SYS_TRUNCATE64
	SNR_FTRUNCATE64                  ScmpSyscall = SYS_FTRUNCATE64
	SNR_STAT64                       ScmpSyscall = SYS_STAT64
	SNR_LSTAT64                      ScmpSyscall = SYS_LSTAT64
	SNR_FSTAT64                      ScmpSyscall = SYS_FSTAT64
	SNR_LCHOWN32                     ScmpSyscall = SYS_LCHOWN32
	SNR_GETUID32                     ScmpSyscall = SYS_GETUID32
	SNR_GETGID32                     ScmpSyscall = SYS_GETGID32
	SNR_GETEUID32                    ScmpSyscall = SYS_GETEUID32
	SNR_GETEGID32                    ScmpSyscall = SYS_GETEGID32
	SNR_SETREUID32                   ScmpSyscall = SYS_SETREUID32
	SNR_SETREGID32                   ScmpSyscall = SYS_SETREGID32
	SNR_GETGROUPS32                  ScmpSyscall = SYS_GETGROUPS32
	SNR_SETGROUPS32                  ScmpSyscall = SYS_SETGROUPS32
	SNR_FCHOWN32                     ScmpSyscall = SYS_FCHOWN32
	SNR_SETRESUID32                  ScmpSyscall = SYS_SETRESUID32
	SNR_GETRESUID32                  ScmpSyscall = SYS_GETRESUID32
	SNR_SETRESGID32                  ScmpSyscall = SYS_SETRESGID32
	SNR_GETRESGID32                  ScmpSyscall = SYS_GETRESGID32
	SNR_CHOWN32                      ScmpSyscall = SYS_CHOWN32
	SNR_SETUID32                     ScmpSyscall = SYS_SETUID32
	SNR_SETGID32                     ScmpSyscall = SYS_SETGID32
	SNR_SETFSUID32                   ScmpSyscall = SYS_SETFSUID32
	SNR_SETFSGID32                   ScmpSyscall = SYS_SETFSGID32
	SNR_PIVOT_ROOT                   ScmpSyscall = SYS_PIVOT_ROOT
	SNR_MINCORE                      ScmpSyscall = SYS_MINCORE
	SNR_MADVISE                      ScmpSyscall = SYS_MADVISE
	SNR_GETDENTS64                   ScmpSyscall = SYS_GETDENTS64
	SNR_FCNTL64                      ScmpSyscall = SYS_FCNTL64
	SNR_GETTID                       ScmpSyscall = SYS_GETTID
	SNR_READAHEAD                    ScmpSyscall = SYS_READAHEAD
	SNR_SETXATTR                     ScmpSyscall = SYS_SETXATTR
	SNR_LSETXATTR                    ScmpSyscall = SYS_LSETXATTR
	SNR_FSETXATTR                    ScmpSyscall = SYS_FSETXATTR
	SNR_GETXATTR                     ScmpSyscall = SYS_GETXATTR
	SNR_LGETXATTR                    ScmpSyscall = SYS_LGETXATTR
	SNR_FGETXATTR                    ScmpSyscall = SYS_FGETXATTR
	SNR_LISTXATTR                    ScmpSyscall = SYS_LISTXATTR
	SNR_LLISTXATTR                   ScmpSyscall = SYS_LLISTXATTR
	SNR_FLISTXATTR                   ScmpSyscall = SYS_FLISTXATTR
	SNR_REMOVEXATTR                  ScmpSyscall = SYS_REMOVEXATTR
	SNR_LREMOVEXATTR                 ScmpSyscall = SYS_LREMOVEXATTR
	SNR_FREMOVEXATTR                 ScmpSyscall = SYS_FREMOVEXATTR
	SNR_TKILL                        ScmpSyscall = SYS_TKILL
	SNR_SENDFILE64                   ScmpSyscall = SYS_SENDFILE64
	SNR_FUTEX                        ScmpSyscall = SYS_FUTEX
	SNR_SCHED_SETAFFINITY            ScmpSyscall = SYS_SCHED_SETAFFINITY
	SNR_SCHED_GETAFFINITY            ScmpSyscall = SYS_SCHED_GETAFFINITY
	SNR_SET_THREAD_AREA              ScmpSyscall = SYS_SET_THREAD_AREA
	SNR_GET_THREAD_AREA              ScmpSyscall = SYS_GET_THREAD_AREA
	SNR_IO_SETUP                     ScmpSyscall = SYS_IO_SETUP
	SNR_IO_DESTROY                   ScmpSyscall = SYS_IO_DESTROY
	SNR_IO_GETEVENTS                 ScmpSyscall = SYS_IO_GETEVENTS
	SNR_IO_SUBMIT                    ScmpSyscall = SYS_IO_SUBMIT
	SNR_IO_CANCEL                    ScmpSyscall = SYS_IO_CANCEL
	SNR_FADVISE64                    ScmpSyscall = SYS_FADVISE64
	SNR_EXIT_GROUP                   ScmpSyscall = SYS_EXIT_GROUP
	SNR_LOOKUP_DCOOKIE               ScmpSyscall = SYS_LOOKUP_DCOOKIE
	SNR_EPOLL_CREATE                 ScmpSyscall = SYS_EPOLL_CREATE
	SNR_EPOLL_CTL                    ScmpSyscall = SYS_EPOLL_CTL
	SNR_EPOLL_WAIT                   ScmpSyscall = SYS_EPOLL_WAIT
	SNR_REMAP_FILE_PAGES             ScmpSyscall = SYS_REMAP_FILE_PAGES
	SNR_SET_TID_ADDRESS              ScmpSyscall = SYS_SET_TID_ADDRESS
	SNR_TIMER_CREATE                 ScmpSyscall = SYS_TIMER_CREATE
	SNR_TIMER_SETTIME                ScmpSyscall = SYS_TIMER_SETTIME
	SNR_TIMER_GETTIME                ScmpSyscall = SYS_TIMER_GETTIME
	SNR_TIMER_GETOVERRUN             ScmpSyscall = SYS_TIMER_GETOVERRUN
	SNR_TIMER_DELETE                 ScmpSyscall = SYS_TIMER_DELETE
	SNR_CLOCK_SETTIME                ScmpSyscall = SYS_CLOCK_SETTIME
	SNR_CLOCK_GETTIME                ScmpSyscall = SYS_CLOCK_GETTIME
	SNR_CLOCK_GETRES                 ScmpSyscall = SYS_CLOCK_GETRES
	SNR_CLOCK_NANOSLEEP              ScmpSyscall = SYS_CLOCK_NANOSLEEP
	SNR_STATFS64                     ScmpSyscall = SYS_STATFS64
	SNR_FSTATFS64                    ScmpSyscall = SYS_FSTATFS64
	SNR_TGKILL                       ScmpSyscall = SYS_TGKILL
	SNR_UTIMES                       ScmpSyscall = SYS_UTIMES
	SNR_FADVISE64_64                 ScmpSyscall = SYS_FADVISE64_64
	SNR_VSERVER                      ScmpSyscall = SYS_VSERVER
	SNR_MBIND                        ScmpSyscall = SYS_MBIND
	SNR_GET_MEMPOLICY                ScmpSyscall = SYS_GET_MEMPOLICY
	SNR_SET_MEMPOLICY                ScmpSyscall = SYS_SET_MEMPOLICY
	SNR_MQ_OPEN                      ScmpSyscall = SYS_MQ_OPEN
	SNR_MQ_UNLINK                    ScmpSyscall = SYS_MQ_UNLINK
	SNR_MQ_TIMEDSEND                 ScmpSyscall = SYS_MQ_TIMEDSEND
	SNR_MQ_TIMEDRECEIVE              ScmpSyscall = SYS_MQ_TIMEDRECEIVE
	SNR_MQ_NOTIFY                    ScmpSyscall = SYS_MQ_NOTIFY
	SNR_MQ_GETSETATTR                ScmpSyscall = SYS_MQ_GETSETATTR
	SNR_KEXEC_LOAD                   ScmpSyscall = SYS_KEXEC_LOAD
	SNR_WAITID                       ScmpSyscall = SYS_WAITID
	SNR_ADD_KEY                      ScmpSyscall = SYS_ADD_KEY
	SNR_REQUEST_KEY                  ScmpSyscall = SYS_REQUEST_KEY
	SNR_KEYCTL                       ScmpSyscall = SYS_KEYCTL
	SNR_IOPRIO_SET                   ScmpSyscall = SYS_IOPRIO_SET
	SNR_IOPRIO_GET                   ScmpSyscall = SYS_IOPRIO_GET
	SNR_INOTIFY_INIT                 ScmpSyscall = SYS_INOTIFY_INIT
	SNR_INOTIFY_ADD_WATCH            ScmpSyscall = SYS_INOTIFY_ADD_WATCH
	SNR_INOTIFY_RM_WATCH             ScmpSyscall = SYS_INOTIFY_RM_WATCH
	SNR_MIGRATE_PAGES                ScmpSyscall = SYS_MIGRATE_PAGES
	SNR_OPENAT                       ScmpSyscall = SYS_OPENAT
	SNR_MKDIRAT                      ScmpSyscall = SYS_MKDIRAT
	SNR_MKNODAT                      ScmpSyscall = SYS_MKNODAT
	SNR_FCHOWNAT                     ScmpSyscall = SYS_FCHOWNAT
	SNR_FUTIMESAT                    ScmpSyscall = SYS_FUTIMESAT
	SNR_FSTATAT64                    ScmpSyscall = SYS_FSTATAT64
	SNR_UNLINKAT                     ScmpSyscall = SYS_UNLINKAT
	SNR_RENAMEAT                     ScmpSyscall = SYS_RENAMEAT
	SNR_LINKAT                       ScmpSyscall = SYS_LINKAT
	SNR_SYMLINKAT                    ScmpSyscall = SYS_SYMLINKAT
	SNR_READLINKAT                   ScmpSyscall = SYS_READLINKAT
	SNR_FCHMODAT                     ScmpSyscall = SYS_FCHMODAT
	SNR_FACCESSAT                    ScmpSyscall = SYS_FACCESSAT
	SNR_PSELECT6                     ScmpSyscall = SYS_PSELECT6
	SNR_PPOLL                        ScmpSyscall = SYS_PPOLL
	SNR_UNSHARE                      ScmpSyscall = SYS_UNSHARE
	SNR_SET_ROBUST_LIST              ScmpSyscall = SYS_SET_ROBUST_LIST
	SNR_GET_ROBUST_LIST              ScmpSyscall = SYS_GET_ROBUST_LIST
	SNR_SPLICE                       ScmpSyscall = SYS_SPLICE
	SNR_SYNC_FILE_RANGE              ScmpSyscall = SYS_SYNC_FILE_RANGE
	SNR_TEE                          ScmpSyscall = SYS_TEE
	SNR_VMSPLICE                     ScmpSyscall = SYS_VMSPLICE
	SNR_MOVE_PAGES                   ScmpSyscall = SYS_MOVE_PAGES
	SNR_GETCPU                       ScmpSyscall = SYS_GETCPU
	SNR_EPOLL_PWAIT                  ScmpSyscall = SYS_EPOLL_PWAIT
	SNR_UTIMENSAT                    ScmpSyscall = SYS_UTIMENSAT
	SNR_SIGNALFD                     ScmpSyscall = SYS_SIGNALFD
	SNR_TIMERFD_CREATE               ScmpSyscall = SYS_TIMERFD_CREATE
	SNR_EVENTFD                      ScmpSyscall = SYS_EVENTFD
	SNR_FALLOCATE                    ScmpSyscall = SYS_FALLOCATE
	SNR_TIMERFD_SETTIME              ScmpSyscall = SYS_TIMERFD_SETTIME
	SNR_TIMERFD_GETTIME              ScmpSyscall = SYS_TIMERFD_GETTIME
	SNR_SIGNALFD4                    ScmpSyscall = SYS_SIGNALFD4
	SNR_EVENTFD2                     ScmpSyscall = SYS_EVENTFD2
	SNR_EPOLL_CREATE1                ScmpSyscall = SYS_EPOLL_CREATE1
	SNR_DUP3                         ScmpSyscall = SYS_DUP3
	SNR_PIPE2                        ScmpSyscall = SYS_PIPE2
	SNR_INOTIFY_INIT1                ScmpSyscall = SYS_INOTIFY_INIT1
	SNR_PREADV                       ScmpSyscall = SYS_PREADV
	SNR_PWRITEV                      ScmpSyscall = SYS_PWRITEV
	SNR_RT_TGSIGQUEUEINFO            ScmpSyscall = SYS_RT_TGSIGQUEUEINFO
	SNR_PERF_EVENT_OPEN              ScmpSyscall = SYS_PERF_EVENT_OPEN
	SNR_RECVMMSG                     ScmpSyscall = __PNR_recvmmsg
	SNR_FANOTIFY_INIT                ScmpSyscall = SYS_FANOTIFY_INIT
	SNR_FANOTIFY_MARK                ScmpSyscall = SYS_FANOTIFY_MARK
	SNR_PRLIMIT64                    ScmpSyscall = SYS_PRLIMIT64
	SNR_NAME_TO_HANDLE_AT            ScmpSyscall = SYS_NAME_TO_HANDLE_AT
	SNR_OPEN_BY_HANDLE_AT            ScmpSyscall = SYS_OPEN_BY_HANDLE_AT
	SNR_CLOCK_ADJTIME                ScmpSyscall = SYS_CLOCK_ADJTIME
	SNR_SYNCFS                       ScmpSyscall = SYS_SYNCFS
	SNR_SENDMMSG                     ScmpSyscall = __PNR_sendmmsg
	SNR_SETNS                        ScmpSyscall = SYS_SETNS
	SNR_PROCESS_VM_READV             ScmpSyscall = SYS_PROCESS_VM_READV
	SNR_PROCESS_VM_WRITEV            ScmpSyscall = SYS_PROCESS_VM_WRITEV
	SNR_KCMP                         ScmpSyscall = SYS_KCMP
	SNR_FINIT_MODULE                 ScmpSyscall = SYS_FINIT_MODULE
	SNR_SCHED_SETATTR                ScmpSyscall = SYS_SCHED_SETATTR
	SNR_SCHED_GETATTR                ScmpSyscall = SYS_SCHED_GETATTR
	SNR_RENAMEAT2                    ScmpSyscall = SYS_RENAMEAT2
	SNR_SECCOMP                      ScmpSyscall = SYS_SECCOMP
	SNR_GETRANDOM                    ScmpSyscall = SYS_GETRANDOM
	SNR_MEMFD_CREATE                 ScmpSyscall = SYS_MEMFD_CREATE
	SNR_BPF                          ScmpSyscall = SYS_BPF
	SNR_EXECVEAT                     ScmpSyscall = SYS_EXECVEAT
	SNR_SOCKET                       ScmpSyscall = __PNR_socket
	SNR_SOCKETPAIR                   ScmpSyscall = __PNR_socketpair
	SNR_BIND                         ScmpSyscall = __PNR_bind
	SNR_CONNECT                      ScmpSyscall = __PNR_connect
	SNR_LISTEN                       ScmpSyscall = __PNR_listen
	SNR_ACCEPT4                      ScmpSyscall = __PNR_accept4
	SNR_GETSOCKOPT                   ScmpSyscall = __PNR_getsockopt
	SNR_SETSOCKOPT                   ScmpSyscall = __PNR_setsockopt
	SNR_GETSOCKNAME                  ScmpSyscall = __PNR_getsockname
	SNR_GETPEERNAME                  ScmpSyscall = __PNR_getpeername
	SNR_SENDTO                       ScmpSyscall = __PNR_sendto
	SNR_SENDMSG                      ScmpSyscall = __PNR_sendmsg
	SNR_RECVFROM                     ScmpSyscall = __PNR_recvfrom
	SNR_RECVMSG                      ScmpSyscall = __PNR_recvmsg
	SNR_SHUTDOWN                     ScmpSyscall = __PNR_shutdown
	SNR_USERFAULTFD                  ScmpSyscall = SYS_USERFAULTFD
	SNR_MEMBARRIER                   ScmpSyscall = SYS_MEMBARRIER
	SNR_MLOCK2                       ScmpSyscall = SYS_MLOCK2
	SNR_COPY_FILE_RANGE              ScmpSyscall = SYS_COPY_FILE_RANGE
	SNR_PREADV2                      ScmpSyscall = SYS_PREADV2
	SNR_PWRITEV2                     ScmpSyscall = SYS_PWRITEV2
	SNR_PKEY_MPROTECT                ScmpSyscall = SYS_PKEY_MPROTECT
	SNR_PKEY_ALLOC                   ScmpSyscall = SYS_PKEY_ALLOC
	SNR_PKEY_FREE                    ScmpSyscall = SYS_PKEY_FREE
	SNR_STATX                        ScmpSyscall = SYS_STATX
	SNR_ARCH_PRCTL                   ScmpSyscall = SYS_ARCH_PRCTL
	SNR_IO_PGETEVENTS                ScmpSyscall = SYS_IO_PGETEVENTS
	SNR_RSEQ                         ScmpSyscall = SYS_RSEQ
	SNR_SEMGET                       ScmpSyscall = __PNR_semget
	SNR_SEMCTL                       ScmpSyscall = __PNR_semctl
	SNR_SHMGET                       ScmpSyscall = __PNR_shmget
	SNR_SHMCTL                       ScmpSyscall = __PNR_shmctl
	SNR_SHMAT                        ScmpSyscall = __PNR_shmat
	SNR_SHMDT                        ScmpSyscall = __PNR_shmdt
	SNR_MSGGET                       ScmpSyscall = __PNR_msgget
	SNR_MSGSND                       ScmpSyscall = __PNR_msgsnd
	SNR_MSGRCV                       ScmpSyscall = __PNR_msgrcv
	SNR_MSGCTL                       ScmpSyscall = __PNR_msgctl
	SNR_CLOCK_GETTIME64              ScmpSyscall = SYS_CLOCK_GETTIME64
	SNR_CLOCK_SETTIME64              ScmpSyscall = SYS_CLOCK_SETTIME64
	SNR_CLOCK_ADJTIME64              ScmpSyscall = SYS_CLOCK_ADJTIME64
	SNR_CLOCK_GETRES_TIME64          ScmpSyscall = SYS_CLOCK_GETRES_TIME64
	SNR_CLOCK_NANOSLEEP_TIME64       ScmpSyscall = SYS_CLOCK_NANOSLEEP_TIME64
	SNR_TIMER_GETTIME64              ScmpSyscall = SYS_TIMER_GETTIME64
	SNR_TIMER_SETTIME64              ScmpSyscall = SYS_TIMER_SETTIME64
	SNR_TIMERFD_GETTIME64            ScmpSyscall = SYS_TIMERFD_GETTIME64
	SNR_TIMERFD_SETTIME64            ScmpSyscall = SYS_TIMERFD_SETTIME64
	SNR_UTIMENSAT_TIME64             ScmpSyscall = SYS_UTIMENSAT_TIME64
	SNR_PSELECT6_TIME64              ScmpSyscall = SYS_PSELECT6_TIME64
	SNR_PPOLL_TIME64                 ScmpSyscall = SYS_PPOLL_TIME64
	SNR_IO_PGETEVENTS_TIME64         ScmpSyscall = SYS_IO_PGETEVENTS_TIME64
	SNR_RECVMMSG_TIME64              ScmpSyscall = SYS_RECVMMSG_TIME64
	SNR_MQ_TIMEDSEND_TIME64          ScmpSyscall = SYS_MQ_TIMEDSEND_TIME64
	SNR_MQ_TIMEDRECEIVE_TIME64       ScmpSyscall = SYS_MQ_TIMEDRECEIVE_TIME64
	SNR_SEMTIMEDOP_TIME64            ScmpSyscall = SYS_SEMTIMEDOP_TIME64
	SNR_RT_SIGTIMEDWAIT_TIME64       ScmpSyscall = SYS_RT_SIGTIMEDWAIT_TIME64
	SNR_FUTEX_TIME64                 ScmpSyscall = SYS_FUTEX_TIME64
	SNR_SCHED_RR_GET_INTERVAL_TIME64 ScmpSyscall = SYS_SCHED_RR_GET_INTERVAL_TIME64
	SNR_PIDFD_SEND_SIGNAL            ScmpSyscall = SYS_PIDFD_SEND_SIGNAL
	SNR_IO_URING_SETUP               ScmpSyscall = SYS_IO_URING_SETUP
	SNR_IO_URING_ENTER               ScmpSyscall = SYS_IO_URING_ENTER
	SNR_IO_URING_REGISTER            ScmpSyscall = SYS_IO_URING_REGISTER
	SNR_OPEN_TREE                    ScmpSyscall = SYS_OPEN_TREE
	SNR_MOVE_MOUNT                   ScmpSyscall = SYS_MOVE_MOUNT
	SNR_FSOPEN                       ScmpSyscall = SYS_FSOPEN
	SNR_FSCONFIG                     ScmpSyscall = SYS_FSCONFIG
	SNR_FSMOUNT                      ScmpSyscall = SYS_FSMOUNT
	SNR_FSPICK                       ScmpSyscall = SYS_FSPICK
	SNR_PIDFD_OPEN                   ScmpSyscall = SYS_PIDFD_OPEN
	SNR_CLONE3                       ScmpSyscall = SYS_CLONE3
	SNR_CLOSE_RANGE                  ScmpSyscall = SYS_CLOSE_RANGE
	SNR_OPENAT2                      ScmpSyscall = SYS_OPENAT2
	SNR_PIDFD_GETFD                  ScmpSyscall = SYS_PIDFD_GETFD
	SNR_FACCESSAT2                   ScmpSyscall = SYS_FACCESSAT2
	SNR_PROCESS_MADVISE              ScmpSyscall = SYS_PROCESS_MADVISE
	SNR_EPOLL_PWAIT2                 ScmpSyscall = SYS_EPOLL_PWAIT2
	SNR_MOUNT_SETATTR                ScmpSyscall = SYS_MOUNT_SETATTR
	SNR_QUOTACTL_FD                  ScmpSyscall = SYS_QUOTACTL_FD
	SNR_LANDLOCK_CREATE_RULESET      ScmpSyscall = SYS_LANDLOCK_CREATE_RULESET
	SNR_LANDLOCK_ADD_RULE            ScmpSyscall = SYS_LANDLOCK_ADD_RULE
	SNR_LANDLOCK_RESTRICT_SELF       ScmpSyscall = SYS_LANDLOCK_RESTRICT_SELF
	SNR_MEMFD_SECRET                 ScmpSyscall = SYS_MEMFD_SECRET
	SNR_PROCESS_MRELEASE             ScmpSyscall = SYS_PROCESS_MRELEASE
	SNR_FUTEX_WAITV                  ScmpSyscall = SYS_FUTEX_WAITV
	SNR_SET_MEMPOLICY_HOME_NODE      ScmpSyscall = SYS_SET_MEMPOLICY_HOME_NODE
	SNR_CACHESTAT                    ScmpSyscall = SYS_CACHESTAT
	SNR_FCHMODAT2                    ScmpSyscall = SYS_FCHMODAT2
	SNR_MAP_SHADOW_STACK             ScmpSyscall = SYS_MAP_SHADOW_STACK
	SNR_FUTEX_WAKE                   ScmpSyscall = SYS_FUTEX_WAKE
	SNR_FUTEX_WAIT                   ScmpSyscall = SYS_FUTEX_WAIT
	SNR_FUTEX_REQUEUE                ScmpSyscall = SYS_FUTEX_REQUEUE
	SNR_STATMOUNT                    ScmpSyscall = SYS_STATMOUNT
	SNR_LISTMOUNT                    ScmpSyscall = SYS_LISTMOUNT
	SNR_LSM_GET_SELF_ATTR            ScmpSyscall = SYS_LSM_GET_SELF_ATTR
	SNR_LSM_SET_SELF_ATTR            ScmpSyscall = SYS_LSM_SET_SELF_ATTR
	SNR_LSM_LIST_MODULES             ScmpSyscall = SYS_LSM_LIST_MODULES
	SNR_MSEAL                        ScmpSyscall = SYS_MSEAL
)
